export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnLEh5ARF6ZmvTIIN2xN
GJdeORkWMnKZXK1NviGofLGxHs6YoXBNasayZcpSoolsAeYuTC01SqFCdV5tjpYV
rg1twcAmNVAWLhgCbraVXt/eCdbk/NJglH06qUnUZxXFn3NpV2H+4RVh+2drD+Rh
7jj7l8xHoObdZYAk6SMbvn/3iItJohWRtbxxM7tNpGf+sym4GsnKwO2N0t/Sokop
fnIFqw6+y4q0vnM6wTuoC84PvjrHjEEkcO6rgt7UriVYYzJZbcOYD3lzFN0GyaGR
DqAnLO0BtNFirF09zG9hlZeT8psahPRtMl/v6m9Rmz/dghH5OkHssEpnTbjmFHIQ
pQIDAQAB
-----END PUBLIC KEY-----
`